services:
  yifen9.li:
    image: ghcr.io/yifen9/yifen9.li
    build:
      context: ..
      dockerfile: Dockerfile.dev
    container_name: yifen9.li
    working_dir: /workspace
    env_file:
      - ../.env.dev
    volumes:
      - "..:/workspace"
    command: >
      bash -c "
        exec sleep infinity
      "